[build]
  base = "frontend"
  command = "npm install --no-audit --no-fund && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = ""
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
